### ISSUE TITLE
slideOffset is Infinity or NaN

### ISSUE THREAD

**Issue by ngThu** [NikoYuwono/ToolbarPanel#2] opened 2016-07-04 12:05 UTC
Many time slideOffset show is Infinity  or >1 or NaN
I don't understand.
If you have free time, please check! Thank so much!

**Comment by NikoYuwono** [comment] 2016-07-20 07:29
@ngThu Sorry for late reply but could you tell me how to reproduce it? And tell me what environment are you working at? Thanks!

**Comment by NikoYuwono** [comment] 2016-11-01 06:29
Closing it for now because unreproducable and need more info how to reproduce it

**Closed as completed by NikoYuwono** 2016-11-01 06:29 UTC
